# Generated by Django 5.0.3 on 2024-04-02 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=13)),
                ('published_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('author_name', models.JSONField(max_length=500)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Book', to='TestApp.author')),
            ],
        ),
    ]
