# Generated by Django 5.0.3 on 2024-04-03 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_image', models.ImageField(null=True, upload_to='dynamic_upload_path')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Book_Image', to='TestApp.book')),
            ],
        ),
    ]
