# Generated by Django 5.0.3 on 2024-04-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_rename_author_name_book_author_remove_book_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='book_code',
        ),
        migrations.RenameField(
            model_name='book_image',
            old_name='book_id',
            new_name='book_code',
        ),
        migrations.AddField(
            model_name='book',
            name='book_details',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
